# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/59e94a66-2a23-4b1c-b61a-604e9a097a3a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A292-2EEF";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/44e04706-80f3-45e0-9753-a94c0ba1e484";
      fsType = "ext4";
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/d370b53c-c14d-42f0-8fde-efaa2690cd55";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c6a5ab56-ba94-4e66-ab4e-7bbfb02aa072"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;
  hardware.pulseaudio.enable = false;
  hardware.opengl.driSupport32Bit = true;
  hardware = {
  	nvidia = {

    		# Modesetting is needed for most wayland compositors
    		modesetting.enable = true;

    		# Enable the nvidia settings menu
    		nvidiaSettings = true;

    		# Optionally, you may need to select the appropriate driver version for your specific GPU.
    		package = config.boot.kernelPackages.nvidiaPackages.legacy_470;
		prime = {
  		  intelBusId = "PCI:0:2:0";
  		  nvidiaBusId = "PCI:2:0:0";
  		};
  	};
  };
}
